TEST_CONTESTS = """
[
  {
    "testid": 68,
    "contest": "OCEANIA-DX-SSB",
    "dat": 1001,
    "wa7bnm": 142,
    "qrzru": 0,
    "startday": 6,
    "starttime": "06:00:00",
    "finishday": 7,
    "finishtime": "05:59:59",
    "rtsbinhours": 0,
    "name": "Oceania DX Phone",
    "cty": "zl",
    "scores": 5,
    "ruleslink": "https://www.oceaniadxcontest.com/rules",
    "logo": "WIA",
    "alias": 0,
    "catcount": 24,
    "wrtc": 0,
    "ttype": 0,
    "annlink": null
  },
  {
    "testid": 166,
    "contest": "TRC-DX",
    "dat": 1001,
    "wa7bnm": 536,
    "qrzru": 0,
    "startday": 6,
    "starttime": "06:00:00",
    "finishday": 7,
    "finishtime": "17:59:59",
    "rtsbinhours": 0,
    "name": "TRC DX",
    "cty": "lz",
    "scores": 2,
    "ruleslink": "https://trcdx.org/rules-trc-dx/",
    "logo": "TRCDX",
    "alias": 0,
    "catcount": 16,
    "wrtc": 0,
    "ttype": 0,
    "annlink": null
  },
  {
    "testid": 360,
    "contest": "RUS-WW-DIGI",
    "dat": 1001,
    "wa7bnm": 570,
    "qrzru": 0,
    "startday": 6,
    "starttime": "12:00:00",
    "finishday": 7,
    "finishtime": "11:59:59",
    "rtsbinhours": 0,
    "name": "Russian WW Digital",
    "cty": "ua",
    "scores": 2,
    "ruleslink": "https://www.rdrclub.ru/russian-ww-digital-contest/51-rus-ww-digi-rules",
    "logo": "RUS-WW-DIGI",
    "alias": 0,
    "catcount": 9,
    "wrtc": 0,
    "ttype": 0,
    "annlink": null
  },
  {
    "testid": 170,
    "contest": "MAKROTHEN-RTTY",
    "dat": 1002,
    "wa7bnm": 159,
    "qrzru": 0,
    "startday": 6,
    "starttime": "00:00:00",
    "finishday": 7,
    "finishtime": "15:59:59",
    "rtsbinhours": 0,
    "name": "Mακροθεν RTTY",
    "cty": "k",
    "scores": 8,
    "ruleslink": "http://www.pl259.org/makrothen/makrothen-rules/",
    "logo": "Makrothen",
    "alias": 0,
    "catcount": 8,
    "wrtc": 0,
    "ttype": 0,
    "annlink": null
  },
  {
    "testid": 67,
    "contest": "OCEANIA-DX-CW",
    "dat": 1002,
    "wa7bnm": 151,
    "qrzru": 0,
    "startday": 6,
    "starttime": "06:00:00",
    "finishday": 7,
    "finishtime": "05:59:59",
    "rtsbinhours": 0,
    "name": "Oceania DX CW",
    "cty": "vk",
    "scores": 8,
    "ruleslink": "https://www.oceaniadxcontest.com/rules",
    "logo": "NZART",
    "alias": 0,
    "catcount": 24,
    "wrtc": 0,
    "ttype": 0,
    "annlink": null
  },
  {
    "testid": 92,
    "contest": "SAC-SSB",
    "dat": 1002,
    "wa7bnm": 131,
    "qrzru": 0,
    "startday": 6,
    "starttime": "12:00:00",
    "finishday": 7,
    "finishtime": "11:59:00",
    "rtsbinhours": 0,
    "name": "Scandinavian Activity SSB",
    "cty": "-",
    "scores": 8,
    "ruleslink": "https://www.sactest.net/blog/scandinavian-activity-contest-2025-rules/",
    "logo": "SAC",
    "alias": 0,
    "catcount": 13,
    "wrtc": 0,
    "ttype": 0,
    "annlink": null
  },
  {
    "testid": 171,
    "contest": "JARTS-WW-RTTY",
    "dat": 1003,
    "wa7bnm": 161,
    "qrzru": 0,
    "startday": 6,
    "starttime": "00:00:00",
    "finishday": 7,
    "finishtime": "23:59:59",
    "rtsbinhours": 0,
    "name": "JARTS WW RTTY",
    "cty": "ja",
    "scores": 14,
    "ruleslink": "http://jarts.jp/",
    "logo": "CQ-HR1",
    "alias": 0,
    "catcount": 3,
    "wrtc": 0,
    "ttype": 0,
    "annlink": null
  },
  {
    "testid": 110,
    "contest": "WAG",
    "dat": 1003,
    "wa7bnm": 163,
    "qrzru": 0,
    "startday": 6,
    "starttime": "15:00:00",
    "finishday": 7,
    "finishtime": "14:59:59",
    "rtsbinhours": 0,
    "name": "Worked All Germany",
    "cty": "dl",
    "scores": 6,
    "ruleslink": "https://www.darc.de/der-club/referate/conteste/worked-all-germany-contest/en/rules/",
    "logo": "WAG",
    "alias": 0,
    "catcount": 8,
    "wrtc": 0,
    "ttype": 0,
    "annlink": null
  },
  {
    "testid": 26,
    "contest": "CQ-WW-SSB",
    "dat": 1004,
    "wa7bnm": 172,
    "qrzru": 0,
    "startday": 6,
    "starttime": "00:00:00",
    "finishday": 7,
    "finishtime": "23:59:59",
    "rtsbinhours": 0,
    "name": "CQ World Wide DX SSB",
    "cty": "k",
    "scores": 8,
    "ruleslink": "https://cqww.com/rules.htm",
    "logo": "CQ",
    "alias": 0,
    "catcount": 47,
    "wrtc": 1,
    "ttype": 0,
    "annlink": null
  }
]
"""
